package com.awakenedredstone.autowhitelist.config;

import com.awakenedredstone.autowhitelist.security.SecureGenerator;
import com.awakenedredstone.moondust.jankson.annotation.Comment;
import com.awakenedredstone.moondust.jankson.annotation.Secret;

import java.util.Base64;

public class MultilinkConfig {
    @Secret
    @Comment("""
      The secret key used for validation of multilink clients.
      On the main server, this is generated by the multilink setup command.
      DO NOT SHARE THIS SECRET!
    """)
    public String secret = SecureGenerator.generateSecret();

    public byte[] secret() {
        return Base64.getDecoder().decode(secret);
    }
}
